### ISSUE TITLE
Design Documents

### ISSUE THREAD

**Issue by andywynkoop** [AbbyTunes/pinterest_clone_project#1]
Hey Abby! Your schema is looking pretty good to me! I just a have a few suggestions:
- [ ] The table names should be `back-ticked`
- [ ] You probably don't need to have a table for images - we'll use active storage (from rails) to handle all of them image associations, so all of your tables that need an image can just attach them directly with that. When you do your sample state though, you'll want to include the urls in your state (for instance, users will have a `imgUrl` on the frontend, but it won't be stored in the users table)

**Comment by AbbyTunes** [comment]
I've modify the tables in schema, and formatted the sample state.
